### ISSUE TITLE
tab template does not integrate well with chart and dropdown

### ISSUE THREAD

**Issue by frostless** [NativeScript/template-tab-navigation-ng#52]
So I tried to integrate this tab template with [chart](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/Chart/getting-started) (one of the NativeScript progress UI)
and [DropDown](https://github.com/PeterStaev/NativeScript-Drop-Down)(a plugin) But I could not get the integrations working.

The chart does not show at all and the dropdown does not render the item list.

But in a simpler HelloWorld template both plugins work.

Here is the [demo app](https://we.tl/htUOvz3BLC) tab app.

I implemented the chart in home tab and dropdown in browser tab.

**Comment by manoldonev** [comment]
The TabsModule in the template is lazy-loaded so you need to move both the DropDownModule and NativeScriptUIChartModule imports from `AppModule` to `TabsModule`:

```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";

import { BrowseComponent } from "./browse/browse.component";
import { HomeComponent } from "./home/home.component";
import { SearchComponent } from "./search/search.component";
import { TabsRoutingModule } from "./tabs-routing.module";
import { TabsComponent } from "./tabs.component";

import { DropDownModule } from "nativescript-drop-down/angular";
import { NativeScriptUIChartModule } from "nativescript-pro-ui/chart/angular";

@NgModule({
    imports: [
        NativeScriptCommonModule,
        TabsRoutingModule,
        DropDownModule,
        NativeScriptUIChartModule
    ],
    declarations: [
        TabsComponent,
        HomeComponent,
        BrowseComponent,
        SearchComponent
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class TabsModule { }
```

Then for the chart in home tab -- in iOS the chart should have a predefined size or otherwise it will either not occupy any space or lead to some side effects depending on its parent layouts. In your case, there is no parent layout thus the control has no predefined size. To overcome this you can wrap the chart in a GridLayout (with rows="*").

As for the dropdown -- we were able to observe the problematic behavior in iOS but it seems you are already in the contact with the plugin authors https://github.com/PeterStaev/NativeScript-Drop-Down/issues/157.

**Comment by frostless** [comment]
Cheers, I got the chart worked now.
