### ISSUE TITLE
Tabview initialisation

### ISSUE THREAD

**Issue by tigerdi** [NativeScript/template-tab-navigation-ng#56]
I am using your template for my app, and on load the tabview loads all three components at once. This is causing some issues for me, as I have an ADAL library authenticating with Azure first to retrieve a token. Then this token is used in all three tab item components to perform http requests. 

I would prefer to use router navigation (with router-outlets?) to change tabs, so then it only loads the component when the tab is clicked. Do you know how this can be done?

**Comment by MartoYankov** [comment]
hi @tigerdi 

The current implementation of the TabView component loads all tabs when it is loaded. We are working on a new implementation that doesn't load all the tabs, but even then it would load adjacent tabs before  they are navigated to. The reason for this is the swipe gesture - we need to know what should be rendered on the next page before it is navigated to, so that we can run the swipe animation.

I think the correct approach to your problem would be to have a loading indicator on your tabs and run your http requests when the tabs are clicked. You can do this with the [selectedIndexChanged](https://docs.nativescript.org/cookbook/ui/tab-view#using-selectedindexchanged-event-from-xml) event.

**Comment by tigerdi** [comment]
Thanks for the info, and I agree that I should be running the http requests on selectedIndexChanged.
